services:
  backend:
    image: ${DOCKER_USER}/docker-project-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - momo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "backend:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.3'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      replicas: 3               
    read_only: true
