services:
  backend:
    image: ${DOCKER_USER}/docker-project-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: backend
    networks:
      - momo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "backend:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.3'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      replicas: 3               
    read_only: true

  frontend:
    image: ${DOCKER_USER}/docker-project-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: frontend
    networks:
      - momo-network    
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "frontend:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.3'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      replicas: 3
    read_only: true
    volumes:
      - nginx-cache:/var/cache/nginx:rw
      - nginx-pid:/var/run:rw

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - momo-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "gateway"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./gateway.conf:/etc/nginx/nginx.conf:ro
      - gateway-cache:/var/cache/nginx:rw
      - gateway-logs:/var/log/nginx:rw

networks:
  momo-network:
    driver: bridge

volumes:
  nginx-cache:
  nginx-pid:
  gateway-cache:
  gateway-logs:
